-- Create a table for dynamic site content (e.g. CEO bio, Hero text, etc.)
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  section_name text unique not null,
  content jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.site_content enable row level security;

-- Policies
-- READ: Public
create policy "Public read site_content" on public.site_content for select to anon using (true);

-- WRITE: Admin (Anon for now as per project convention)
create policy "Anon all site_content" on public.site_content for all to anon using (true);
