-- 1. Services Table
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null,
  icon_name text,
  description text,
  full_description text,
  scope text[], -- Array of strings
  image text, -- Base64 or URL
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Projects Table
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  image text, -- Base64 or URL
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table public.services enable row level security;
alter table public.projects enable row level security;

-- 4. Policies (Public Read, Anon Write for Admin Panel)
-- READ: Everyone can see
create policy "Public read services" on public.services for select to anon using (true);
create policy "Public read projects" on public.projects for select to anon using (true);

-- WRITE/UPDATE/DELETE: Anon allowed (Since we are using simple password auth in frontend)
-- For higher security, implement Supabase Auth and restrict these to 'authenticated' role.
create policy "Anon all services" on public.services for all to anon using (true);
create policy "Anon all projects" on public.projects for all to anon using (true);
