-- Migration to add contacts table

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  message text,
  status text default 'New', -- New, Contacted, Converted, Archives
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.contacts enable row level security;

-- Policies (Consistent with existing 'Open' security model for MVP)
create policy "Anon all contacts" on public.contacts for all to anon using (true);
